name: 'Get App Version'
description: 'Retrieve the application version using `make get-version`.'

inputs:

outputs:
  SHORT_SHA:
    description: 'The short SHA of the commit'
    value: ${{ steps.get_app_version.outputs.short_sha }}
  APP_VERSION:
    description: 'The application version'
    value: ${{ steps.get_app_version.outputs.app_version }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get App Version
      id: get_app_version
      shell: bash
      run: |
        echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        echo "app_version=$(make get-version)" >> $GITHUB_OUTPUT
